let words = [
    [ "Earth",  "Planet inhabited by humans"],
    [ "Keyboard",  "A common input device used in computers"],
    [ "Python",  "An snake or a high level programming language"],
    [ "Alaska",  "The biggest state in the United states of America"],
    [ "Backspace",  "Keyboard key used to delete last typed character"],
    [ "wool",  "Obtained from sheep"],
    [ "Sun",  "The star that provides light for humans"],
    [ "USD",  "Common currency used in the United states of America"],
    [ "Binary",  "Language that machines understand"],
    [ "Transistor",  "Semiconductor device used to amplify or switch electrical signals and power"],
    [ "Topeka",  "Capital of the state Kansas"],
    [ "Cairo",  "Capital of egypt"],
    [ "Google",  "Most popular search engine as of 2022 used for searching the world wide web"],
    [ "Agriculture",  "The science or practice of farming"],
    [ "Pacific",  "Word for being peaceful"],
    [ "Mountain",  "A large natural elevation of the Earth's surface"],
    [ "Dazzling",  "Extremely bright and beautiful"],
    [ "Youtube",  "Popular media streaming website that was launched on December 15, 2005"],
    [ "Facebook",
      "Popular social networking website with a movie made after it called \"The social network\" "],
    [ "Brazil",  "Biggest country in South America"],
    [ "Battery",
      "A electronic equipment that holds power also can be defined in law as unconsented physical contact"],
    [ "Tokyo",  "Capital city of Japan"],
    [ "Java",  "An island in Indonesia or can also be defined as a programming language"],
    [ "Wikipedia",  "A free encyclopedia on the internet"],
    [ "Internet",  "A global computer network invented on January 1, 1983"],
    [ "Protocol",  "A set of rules governing the exchange or transmission of data between devices."],
    [ "Bolivia",  "A country in South America with red, yellow, and green on its flag"],
    [ "Worldwide",  "Word for extending or reacing throughout the world"],
    [ "Clock",  "Mechanical device used to see time"],
    [ "Time",
      "The indefinite continued progress of existence and events in the past, present, and future regarded as a whole"],
    [ "Cat", "A feline animal"],
    [ "Computer",  "an electronic device for storing and processing data, typically in binary form, according to instructions given to it in a variable program."],
    [ "Eyes",  "The body part used to see"],
    [ "Water",  "H20"],
    [ "Sound",  "vibrations that travel through the air or another medium and can be heard when they reach a person's or animal's ear."],
    [ "Oxygen",  "O"],
    [ "Oxford",  "Famous dictionary"],
    [ "Tree",  "a woody perennial plant, typically having a single stem or trunk growing to a considerable height and bearing lateral branches at some distance from the ground."],
    [ "Mouse",  "A computer input device also can be defined as an animal"],
    [ "Meteor",  "a small body of matter from outer space that enters the earth's atmosphere, becoming incandescent as a result of friction and appearing as a streak of light."],
    [ "Apple",  "A fruit also can be defined as a large tech company"],
    [ "Silicon",  "the chemical element of atomic number 14, a nonmetal with semiconducting properties, used in making electronic circuits."],
    [ "Gigantic",  "Big"],
    [ "Dictionary",  "A book with definitions of words"],
    [ "Clever",  "quick to understand, learn, and devise or apply ideas; intelligent."],
    [ "North",  "the direction in which a compass needle normally points, toward the horizon on the left-hand side of a person facing east, or the part of the horizon lying in this direction."],
    [ "Compass",  "an instrument containing a magnetized pointer which shows the direction of magnetic north and bearings from it."],
    [ "Latitude",  "the angular distance of a place north or south of the earth's equator, or of a celestial object north or south of the celestial equator, usually expressed in degrees and minutes."],
    [ "Longitude",  "the angular distance of a place east or west of the meridian at Greenwich, England, or west of the standard meridian of a celestial object, usually expressed in degrees and minutes."],
    [ "Gravity",  "the force that attracts a body toward the center of the earth, or toward any other physical body having mass."],
    [ "Insane",  "in a state of mind which prevents normal perception, behavior, or social interaction; seriously mentally ill."],
    [ "Alphabet",  "ABCDEFGHIJKLMNOPQRSTUVWXYZ"],
    [ "Definition",  "a statement of the exact meaning of a word, especially in a dictionary."],
    [ "Website",  "a set of related web pages located under a single domain name, typically produced by a single person or organization."],
    [ "Trigonometry",  "The study of triangles"],
    [ "Anchor",  "a heavy object attached to a rope or chain and used to moor a vessel to the sea bottom, typically one having a metal shank with a ring at one end for the rope and a pair of curved and/or barbed flukes at the other."],
    [ "Everybody",  "every person"],
    [ "Shell",  "The thing on a turtle's back thats hard"],
    [ "for",  "used as a function word to indicate purpose also can be defined as a way to start a loop in programming"],
    [ "Hundred",  "100"]
]